#!/bin/bash

# Setup script for Java decompilers used by Maven Decoder MCP Server

set -e

echo "Setting up Java decompilers for Maven Decoder MCP Server..."

# Create decompilers directory
mkdir -p decompilers
cd decompilers

# Download CFR decompiler
echo "Downloading CFR decompiler..."
if [ ! -f "cfr.jar" ]; then
    wget -q "https://www.benf.org/other/cfr/cfr-0.152.jar" -O cfr.jar
    echo "✓ CFR decompiler downloaded"
else
    echo "✓ CFR decompiler already exists"
fi

# Download Procyon decompiler
echo "Downloading Procyon decompiler..."
if [ ! -f "procyon-decompiler.jar" ]; then
    wget -q "https://github.com/mstrobel/procyon/releases/download/v0.6.0/procyon-decompiler-0.6.0.jar" -O procyon-decompiler.jar
    echo "✓ Procyon decompiler downloaded"
else
    echo "✓ Procyon decompiler already exists"
fi

# Note about Fernflower
echo ""
echo "Note: Fernflower decompiler is included with IntelliJ IDEA."
echo "If you have IntelliJ IDEA installed, you can find it at:"
echo "  Linux/Mac: <IDEA_HOME>/plugins/java-decompiler/lib/java-decompiler.jar"
echo "  Windows: <IDEA_HOME>\\plugins\\java-decompiler\\lib\\java-decompiler.jar"
echo ""

cd ..

# Update decompiler paths in the configuration
echo "Updating decompiler configuration..."
cat > decompiler_paths.py << EOF
"""
Decompiler paths configuration
Auto-generated by setup_decompilers.sh
"""

DECOMPILER_PATHS = {
    'cfr': 'decompilers/cfr.jar',
    'procyon': 'decompilers/procyon-decompiler.jar',
    # Uncomment and update path if you have Fernflower
    # 'fernflower': 'path/to/java-decompiler.jar'
}
EOF

echo "✓ Decompiler setup complete!"
echo ""
echo "Available decompilers:"
echo "  - CFR: decompilers/cfr.jar"
echo "  - Procyon: decompilers/procyon-decompiler.jar"
echo "  - javap: Built-in with JDK"
echo ""
echo "To test the decompilers, run:"
echo "  java -jar decompilers/cfr.jar --help"
echo "  java -jar decompilers/procyon-decompiler.jar --help"
echo ""
