"""
Decompiler paths configuration
Auto-generated by setup_decompilers.sh
"""

DECOMPILER_PATHS = {
    'cfr': 'decompilers/cfr.jar',
    'procyon': 'decompilers/procyon-decompiler.jar',
    # Uncomment and update path if you have Fernflower
    # 'fernflower': 'path/to/java-decompiler.jar'
}
